import { Product } from "./types/Product";

export const sampleProducts: Product[] = [
  {
    name: "Nike Slim Shirt",
    slug: "nike-slim-shirt",
    image: "../images/p1.jpg",
    category: "Shirts",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "highh quality shirt",
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "Adidas Fit Shirt",
    slug: "adidas-fit-shirt",
    image: "../images/p2.jpg",
    category: "Shirts",
    brand: "Adidas",
    price: 100,
    countInStock:210,
    description: "highh quality shirt",
    rating: 4.0,
    numReviews: 10,
  },
  {
    name: "Lacoste Free Pants",
    slug: "lacoste-free-pants",
    image: "../images/p3.jpg",
    category: "Pants",
    brand: "Lacoste",
    price: 200,
    countInStock: 0,
    description: "highh quality shirt",
    rating: 4.8,
    numReviews: 17,
  },
  {
    name: "Nike Slim Pants",
    slug: "nike-slim-pants",
    image: "../images/p4.jpg",
    category: "pants",
    brand: "Nike",
    price: 70,
    countInStock: 13,
    description: "highh quality shirt",
    rating: 4.5,
    numReviews: 14,
  },
];
